{{
    config(materialized='table')
}}

-- Mock Qualifyze internal site registry. FULLY STATIC.
-- Generated by scripts/regenerate_master.py from searchGMPCExport_5451317683799439071.xls
-- DO NOT edit by hand unless you know what you're doing; rerun the
-- script against a fresh Excel to refresh the exact-match block.

select 'QZ-00001' as qualifyze_site_id,
       'LOC-100000729' as oms_location_id,
       'Goodwill Pharma Plc.' as canonical_name,
       'Cserzy Mihaly Utca 32' as canonical_address,
       'Szeged' as city,
       'Hungary' as country
union all
select 'QZ-00002' as qualifyze_site_id,
       'LOC-100001474' as oms_location_id,
       'Novo Nordisk A/S' as canonical_name,
       'Hallas Alle 1' as canonical_address,
       'Kalundborg' as city,
       'Denmark' as country
union all
select 'QZ-00003' as qualifyze_site_id,
       'LOC-100003599' as oms_location_id,
       'PROTINA Pharmazeutische GmbH' as canonical_name,
       'Adalperostrasse 90' as canonical_address,
       'Ismaning' as city,
       'Germany' as country
union all
select 'QZ-00004' as qualifyze_site_id,
       'LOC-100007621' as oms_location_id,
       'OPTOPAN Pharma GmbH' as canonical_name,
       'Adalperostrasse 90' as canonical_address,
       'Ismaning' as city,
       'Germany' as country
union all
select 'QZ-00005' as qualifyze_site_id,
       'LOC-100007914' as oms_location_id,
       'Octapharma Plasma GmbH' as canonical_name,
       'Webergasse 1' as canonical_address,
       'Dresden' as city,
       'Germany' as country
union all
select 'QZ-00006', cast(null as text), 'Astra Nordic Manufacturing AB', 'Industrigatan 12', 'Sodertalje', 'Sweden'
union all
select 'QZ-00007', cast(null as text), 'Pasteur Bio Industries SAS', '23 Rue de la Convention', 'Lyon', 'France'
union all
select 'QZ-00008', cast(null as text), 'Bavarian Pharma Werke GmbH', 'Industriestrasse 45', 'Munich', 'Germany'
union all
select 'QZ-00009', cast(null as text), 'Hibernia Sterile Solutions Ltd', '14 Riverside Park', 'Dublin', 'Ireland'
union all
select 'QZ-00010', cast(null as text), 'Iberica Lifesciences SL', 'Calle del Sol 7', 'Barcelona', 'Spain'
