"""Generate a tiny test Excel for pipeline edge-case validation.

Produces data/raw/test_data.xlsx with 5 rows that exercise:
  - R1: valid baseline row (sanity check, should appear in bronze_eudragmdp)
  - R2: oms_location_id = NULL              -> bronze_rejected
  - R3: inspection_end_date = 'not-a-date'  -> bronze_eudragmdp with
        inspection_end_date NULL (date() of an invalid string -> NULL in SQLite)
  - R4: valid duplicate row (same eudragmdp_doc_ref as R5)
  - R5: identical to R4 -> exposes the duplicate via the unique test on
        bronze_eudragmdp.eudragmdp_doc_ref

Usage:
    cd ~/Desktop/Q/qualifyze_pipeline
    source .venv/bin/activate
    python scripts/generate_test_excel.py
"""
from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT = PROJECT_ROOT / "data" / "raw" / "test_data.xlsx"

HEADERS = [
    "Certificate Number",
    "EudraGMDP Document Reference Number",
    "Document Type",
    "MIA Number",
    "OMS Organisation Identifier",
    "OMS Location Identifier",
    "Site Name",
    "Address 1",
    "Address 2",
    "Address 3",
    "Address 4",
    "City",
    "Postcode",
    "Country",
    "DUNS Number",
    "Site NCA Reference",
    "Inspection End Date",
    "Issue Date",
    "Last Updated Date",
]

# 5 rows, in the same column order as HEADERS.
ROWS = [
    # R1 - valid baseline
    [
        "CERT-T001", "DOC-T001", "GMPC", "MIA-T001",
        "ORG-T001", "OMS-T001", "Test Pharma Valid SRL",
        "Strada Test 1", None, None, None,
        "Bucharest", "010101", "Romania",
        "111111111", "NCA-T001",
        "2025-06-15", "2025-07-01", "2025-07-01",
    ],
    # R2 - oms_location_id = NULL  -> bronze_rejected
    [
        "CERT-T002", "DOC-T002", "GMPC", "MIA-T002",
        "ORG-T002", None, "Test Pharma NoOms SRL",
        "Strada Test 2", None, None, None,
        "Cluj-Napoca", "400000", "Romania",
        "222222222", "NCA-T002",
        "2025-06-20", "2025-07-05", "2025-07-05",
    ],
    # R3 - bad inspection_end_date  -> passes validation but date() returns NULL
    [
        "CERT-T003", "DOC-T003", "GMPNC", "MIA-T003",
        "ORG-T003", "OMS-T003", "Test Pharma BadDate SRL",
        "Strada Test 3", None, None, None,
        "Iasi", "700000", "Romania",
        "333333333", "NCA-T003",
        "not-a-date", "2025-07-10", "2025-07-10",
    ],
    # R4 - duplicate pair (same eudragmdp_doc_ref as R5)
    [
        "CERT-T004", "DOC-T004", "GMPC", "MIA-T004",
        "ORG-T004", "OMS-T004", "Test Pharma Duplicate SRL",
        "Strada Test 4", None, None, None,
        "Timisoara", "300000", "Romania",
        "444444444", "NCA-T004",
        "2025-06-25", "2025-07-15", "2025-07-15",
    ],
    # R5 - identical to R4
    [
        "CERT-T004", "DOC-T004", "GMPC", "MIA-T004",
        "ORG-T004", "OMS-T004", "Test Pharma Duplicate SRL",
        "Strada Test 4", None, None, None,
        "Timisoara", "300000", "Romania",
        "444444444", "NCA-T004",
        "2025-06-25", "2025-07-15", "2025-07-15",
    ],
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()
    ws = wb.active
    ws.title = "Sheet1"

    # Rows 1-4 mimic the metadata block of the real EudraGMDP export so the
    # ingest header detector still finds the header at row 5.
    ws.cell(row=1, column=1, value="EudraGMDP Search Export (TEST DATA)")
    ws.cell(row=2, column=1, value="Generated by scripts/generate_test_excel.py")
    ws.cell(row=3, column=1, value="")
    ws.cell(row=4, column=1, value="")

    # Row 5 = headers
    for col, header in enumerate(HEADERS, start=1):
        ws.cell(row=5, column=col, value=header)

    # Rows 6+ = data
    for ridx, row in enumerate(ROWS, start=6):
        for cidx, value in enumerate(row, start=1):
            ws.cell(row=ridx, column=cidx, value=value)

    wb.save(OUT)
    print(f"Wrote {len(ROWS)} test rows to {OUT}")


if __name__ == "__main__":
    main()
