"""Regenerate dbt_project/models/gold/gold_master_site.sql from a real Excel.

Reads the EudraGMDP export, picks the first N (default 5) distinct
oms_location_id values, and writes a fully static SQL file with:
  - those N rows as exact-match candidates (QZ-00001..QZ-0000N)
  - 5 hardcoded EU mock sites with oms_location_id = NULL as fuzzy candidates

The output file contains plain SQL inserts, no ref() to bronze, no logic.
You run this once per Excel export, then commit the resulting SQL.

Usage:
    cd ~/Desktop/Q/qualifyze_pipeline
    source .venv/bin/activate
    python scripts/regenerate_master.py data/raw/searchGMPCExport_5451317683799439071.xls
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

# Make 'ingest' importable regardless of cwd.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from ingest import (  # noqa: E402
    EUDRAGMDP_COLUMN_RENAME,
    _detect_header_row,
    _pick_engine,
)

OUT_PATH = PROJECT_ROOT / "dbt_project" / "models" / "gold" / "gold_master_site.sql"

FUZZY_MOCKS = [
    ("QZ-00006", "Astra Nordic Manufacturing AB", "Industrigatan 12",
     "Sodertalje", "Sweden"),
    ("QZ-00007", "Pasteur Bio Industries SAS", "23 Rue de la Convention",
     "Lyon", "France"),
    ("QZ-00008", "Bavarian Pharma Werke GmbH", "Industriestrasse 45",
     "Munich", "Germany"),
    ("QZ-00009", "Hibernia Sterile Solutions Ltd", "14 Riverside Park",
     "Dublin", "Ireland"),
    ("QZ-00010", "Iberica Lifesciences SL", "Calle del Sol 7",
     "Barcelona", "Spain"),
]


def _sql_lit(v) -> str:
    if pd.isna(v) or v is None:
        return "null"
    s = str(v).replace("'", "''")
    return f"'{s}'"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("file", help="Path to the EudraGMDP Excel export.")
    p.add_argument("--n", type=int, default=5,
                   help="How many exact-match sites to keep (default 5).")
    args = p.parse_args()

    src = Path(args.file).resolve()
    if not src.exists():
        sys.exit(f"File not found: {src}")

    engine = _pick_engine(src)
    header_row = _detect_header_row(src, engine)
    df = pd.read_excel(src, engine=engine, header=header_row)
    df.columns = [str(c).strip() for c in df.columns]
    df = df.rename(columns=EUDRAGMDP_COLUMN_RENAME)

    sites = (
        df[df["oms_location_id"].notnull()]
        .drop_duplicates(subset=["oms_location_id"])
        .sort_values("oms_location_id")
        .head(args.n)
    )
    if len(sites) < args.n:
        print(f"WARNING: only {len(sites)} distinct oms_location_id available "
              f"(requested {args.n}); will produce {len(sites)} exact-match "
              f"rows.", file=sys.stderr)

    lines = [
        "{{",
        "    config(materialized='table')",
        "}}",
        "",
        "-- Mock Qualifyze internal site registry. FULLY STATIC.",
        "-- Generated by scripts/regenerate_master.py from "
        f"{src.name}",
        "-- DO NOT edit by hand unless you know what you're doing; rerun the",
        "-- script against a fresh Excel to refresh the exact-match block.",
        "",
    ]

    first = True
    for i, (_, row) in enumerate(sites.iterrows(), start=1):
        qz = f"QZ-{i:05d}"
        prefix = "select " if first else "union all\nselect "
        first = False
        lines.append(
            f"{prefix}{_sql_lit(qz)} as qualifyze_site_id,\n"
            f"       {_sql_lit(row.get('oms_location_id'))} as oms_location_id,\n"
            f"       {_sql_lit(row.get('site_name'))} as canonical_name,\n"
            f"       {_sql_lit(row.get('address_1'))} as canonical_address,\n"
            f"       {_sql_lit(row.get('city'))} as city,\n"
            f"       {_sql_lit(row.get('country'))} as country"
        )

    for qz, name, addr, city, country in FUZZY_MOCKS:
        lines.append(
            f"union all\nselect {_sql_lit(qz)}, "
            f"cast(null as text), "
            f"{_sql_lit(name)}, "
            f"{_sql_lit(addr)}, "
            f"{_sql_lit(city)}, "
            f"{_sql_lit(country)}"
        )

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(sites)} exact + {len(FUZZY_MOCKS)} fuzzy rows to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
